#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 10 20:14:59 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
