#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 11 20:14:05 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9 + EuphoriaPatches_1.10.0
